### ISSUE TITLE
Webapp fails to import new Jenkins jobs

### ISSUE THREAD

**Issue by hribeiro-jnpr** [Juniper/nita-webapp#24]
Having Jenkins updated to version 2.235.5 seems to break the "network_template_mgr" and "network_type_validator" webapp jobs functionality.

The webapp becomes unable to create jobs when creating new networks.

From the log: [network_template_mgr_10_log.txt](https://github.com/Juniper/nita-jenkins/files/7227240/network_template_mgr_10_log.txt)

The relevant lines are:
`python3 /var/jenkins_scripts/adapt_project_yaml.py -n dc-1 -d "dc-1 created using the NITA webapp" -f /project/evpn_vxlan_erb_dc_1.1-dc-1/project.yaml -c:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.`
and
`Error: Unable to access jarfile /var/jenkins_home/war/WEB-INF/jenkins-cli.jar`

This issue relates to Juniper/nita-jenkins#4

**Comment by aburston** [comment]
This was resolved in 22.8.
