### ISSUE TITLE
View hyperlink for Console logs not working in nita-webapp UI 

### ISSUE THREAD

**Issue by NarenderVaishnav** [Juniper/nita-webapp#6]
View link for Console log output is not redirecting to console log output . 
The View link is going to port 8080 instead of 8443. (http://webapp:8080/job/test_bt-sample/2/console)

<img width="1147" alt="Screenshot 2021-04-12 at 1 51 02 PM" src="https://user-images.githubusercontent.com/82391464/114407699-4e096300-9bc6-11eb-980e-61d3e97fe463.png">

**Comment by hribeiro-jnpr** [comment]
As of commit [706a21dae6265548a105d1542fc94473fa6e66bd](https://github.com/Juniper/nita-webapp/commit/706a21dae6265548a105d1542fc94473fa6e66bd) the following feature is added:
## Set Jekins URL

By default the Webapp assumes a local installation. If this is not the case and you have Nita running on a remote machine you can configure the Webapp to properly riderect the user to the Jenkins UI.

You only need to set the environment variable ``HOST_URL`` with the address of the remote machine and the variable ``JENKINS_PORT`` with the port that Jenkins is listening on.

Example:
```
export HOST_URL=remoteserver.com
export JENKINS_PORT=8443
```

**Comment by hribeiro-jnpr** [comment]
Changed variable name. See bellow!

## Set Jekins URL

By default the Webapp assumes a local installation. If this is not the case and you have Nita running on a remote machine you can configure the Webapp to properly riderect the user to the Jenkins UI.

You only need to set the environment variable ``JENKINS_URL`` with the address of the remote machine and the variable ``JENKINS_PORT`` with the port that Jenkins is listening on.

Example:
```
export JENKINS_URL=remoteserver.com
export JENKINS_PORT=8443
```
